# Generated by Django 3.2.4 on 2021-06-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCourseScheduleTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('coursesubtitle', models.CharField(blank=True, db_column='courseSubtitle', max_length=300, null=True)),
                ('coursename', models.CharField(blank=True, db_column='courseName', max_length=500, null=True)),
                ('coursedescription', models.TextField(blank=True, db_column='courseDescription', null=True)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('coursetype', models.CharField(blank=True, db_column='courseType', max_length=100, null=True)),
            ],
            options={
                'db_table': 'view_course_schedule_trainer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=500)),
                ('courseSubtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('courseDescription', models.TextField(blank=True, max_length=5000, null=True)),
                ('coursePrice', models.FloatField()),
                ('isCourseFree', models.BooleanField(default=True)),
                ('isCourseActive', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_courses/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.coursecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountCode', models.CharField(max_length=50)),
                ('procent', models.FloatField()),
                ('validFrom', models.DateTimeField(blank=True, null=True)),
                ('validTo', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateInactive', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('about', models.TextField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('teamRole', models.TextField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=300, null=True)),
                ('linkedIn', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='logo_reviews/')),
                ('review', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerPrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.courses')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('courseLink', models.CharField(blank=True, max_length=100, null=True)),
                ('courseType', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerPrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.courses')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_name', to='dashboard_app.team'),
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('lastJob', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('reference', models.CharField(blank=True, choices=[('FACEBOOK', 'FACEBOOK'), ('INSTAGRAM', 'INSTAGRAM'), ('LINKEDIN', 'LINKEDIN'), ('RECLAME INTERNET', 'RECLAME INTERNET'), ('RECLAME MEDIA', 'RECLAME MEDIA'), ('PRIETENI', 'PRIETENI'), ('ALTELE', 'ALTELE')], max_length=30, null=True)),
                ('is_career', models.BooleanField(default=True)),
                ('is_business', models.BooleanField(default=False)),
                ('has_recommended', models.BooleanField(blank=True, default=False, null=True)),
                ('acord_gdpr', models.BooleanField(default=False)),
                ('course_registered', models.ManyToManyField(related_name='course_name', to='dashboard_app.Courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_app.discount'),
        ),
        migrations.AddField(
            model_name='courses',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='dashboard_app.member'),
        ),
        migrations.AddField(
            model_name='courses',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer', to='dashboard_app.member'),
        ),
    ]
