# Generated by Django 3.2.4 on 2021-06-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_last_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(max_length=1500)),
                ('submited_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='learner',
            name='reference',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('De la un prieten / o ruda', 'De la un prieten / o ruda'), ('De la un coleg / colaborator', 'De la un coleg / colaborator'), ('De la managerul meu', 'De la managerul meu'), ('Alta sursa', 'Alta sursa')], max_length=30, null=True),
        ),
    ]
