# Generated by Django 3.2 on 2021-06-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_auto_20210611_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='has_participated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
