# Generated by Django 3.2 on 2021-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_learner_has_participated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRegistredParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('courselink', models.CharField(blank=True, db_column='courseLink', max_length=100, null=True)),
                ('coursename', models.CharField(blank=True, db_column='courseName', max_length=500, null=True)),
                ('days_from_register', models.FloatField(blank=True, null=True)),
                ('weeks_to_course', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_registred_participants',
                'managed': False,
            },
        ),
    ]
