# Generated by Django 3.2 on 2021-06-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_viewregistredparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='allow_newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
