# Generated by Django 3.2 on 2021-06-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_learner_allow_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_participated', models.BooleanField(blank=True, default=False, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard_app.schedule')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.learner')),
            ],
        ),
    ]
