# Generated by Django 3.2 on 2021-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPrezenta',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('courses_id', models.IntegerField(blank=True, null=True)),
                ('coursename', models.CharField(blank=True, db_column='courseName', max_length=500, null=True)),
                ('trainerfirstname', models.CharField(blank=True, db_column='trainerFirstName', max_length=100, null=True)),
                ('trainerlastname', models.CharField(blank=True, db_column='trainerLastName', max_length=100, null=True)),
                ('trainer_id', models.IntegerField(blank=True, null=True)),
                ('learnerfirstname', models.CharField(blank=True, db_column='learnerFirstName', max_length=50, null=True)),
                ('learnerlastname', models.CharField(blank=True, db_column='learnerLastName', max_length=50, null=True)),
                ('learnermail', models.CharField(blank=True, db_column='learnerMail', max_length=100, null=True)),
                ('learnerphone', models.CharField(blank=True, db_column='learnerPhone', max_length=20, null=True)),
                ('learner_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_prezenta',
                'managed': False,
            },
        ),
    ]
