# Generated by Django 3.1.3 on 2021-05-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_auto_20210522_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseDescription',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
