# Generated by Django 3.1.3 on 2021-05-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0016_auto_20210524_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseSubtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
