# Generated by Django 3.1.3 on 2021-05-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0017_courses_coursesubtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='courseType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
