# Generated by Django 3.1.3 on 2021-05-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0018_schedule_coursetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCourseScheduleTrainer',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('coursesubtitle', models.CharField(blank=True, db_column='courseSubtitle', max_length=300, null=True)),
                ('coursename', models.CharField(blank=True, db_column='courseName', max_length=500, null=True)),
                ('coursedescription', models.TextField(blank=True, db_column='courseDescription', null=True)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('coursetype', models.CharField(blank=True, db_column='courseType', max_length=100, null=True)),
            ],
            options={
                'db_table': 'view_course_schedule_trainer',
                'managed': False,
            },
        ),
    ]
