# Generated by Django 3.1.3 on 2021-05-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0021_member_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
