# Generated by Django 3.1.3 on 2021-05-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_auto_20210416_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('lastJob', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('reference', models.CharField(blank=True, choices=[('FACEBOOK', 'FACEBOOK'), ('INSTAGRAM', 'INSTAGRAM'), ('LINKEDIN', 'LINKEDIN'), ('RECLAME INTERNET', 'RECLAME INTERNET'), ('RECLAME MEDIA', 'RECLAME MEDIA'), ('PRIETENI', 'PRIETENI'), ('ALTELE', 'ALTELE')], max_length=30, null=True)),
                ('is_career', models.BooleanField(default=True)),
                ('is_business', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerSubmittedToCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks_student', models.TextField(blank=True, max_length=300, null=True)),
                ('remarks_trainer', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=100)),
                ('dateCreation', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateInactive', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='owners/')),
                ('remarks', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DiscountsPacks',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='classInfo',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='student',
        ),
        migrations.RemoveField(
            model_name='soldcourses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='soldcourses',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='soldcourses',
            name='student',
        ),
        migrations.RemoveField(
            model_name='students',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='targets',
            name='course',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='team',
        ),
        migrations.RenameField(
            model_name='coursecategory',
            old_name='name',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='description',
            new_name='courseDescription',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='name',
            new_name='courseName',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='pret',
            new_name='coursePrice',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='active',
            new_name='isCourseActive',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='free',
            new_name='isCourseFree',
        ),
        migrations.AddField(
            model_name='courses',
            name='courseLink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobdomains',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ownerprc',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainerprc',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
        migrations.DeleteModel(
            name='SoldCourses',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Targets',
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_app.team'),
        ),
        migrations.AddField(
            model_name='member',
            name='teamRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_app.teamrole'),
        ),
        migrations.AddField(
            model_name='learnersubmittedtocourses',
            name='classInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard_app.schedule'),
        ),
        migrations.AddField(
            model_name='learnersubmittedtocourses',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard_app.learner'),
        ),
        migrations.AddField(
            model_name='learner',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_app.jobdomains'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='dashboard_app.member'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer', to='dashboard_app.member'),
        ),
        migrations.AlterField(
            model_name='ownerprc',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.member'),
        ),
        migrations.AlterField(
            model_name='trainerprc',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.member'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
