# Generated by Django 3.1.3 on 2021-05-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_auto_20210522_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseDescription',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobdomains',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
