# Generated by Django 3.1.3 on 2021-05-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0009_auto_20210522_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
