# Generated by Django 3.1.3 on 2021-05-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0013_auto_20210522_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='course_registered',
            field=models.ManyToManyField(related_name='course_name', to='dashboard_app.Courses'),
        ),
    ]
