# Generated by Django 3.1.3 on 2021-05-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0014_auto_20210522_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='acord_gdpr',
            field=models.BooleanField(default=False),
        ),
    ]
