# Generated by Django 3.1.3 on 2021-05-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0015_learner_acord_gdpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
