# Generated by Django 3.2 on 2021-06-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0024_auto_20210604_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailPictures',
        ),
    ]
