# Generated by Django 3.2 on 2021-06-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0025_delete_mailpictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='has_recommended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
