# Generated by Django 3.2 on 2021-06-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0026_learner_has_recommended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewcoursescheduletrainer',
            options={'managed': True},
        ),
    ]
