# Generated by Django 3.2 on 2021-06-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0027_alter_viewcoursescheduletrainer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcoursescheduletrainer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
