# Generated by Django 3.2 on 2021-06-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0028_alter_viewcoursescheduletrainer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewcoursescheduletrainer',
            options={'managed': False},
        ),
    ]
